[project]
name = "bai-tap-nhom-mnm"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=1.26.0,<2.4.0",
    "pandas>=2.0.0,<3.0.0",
    "pandas-stubs~=2.3.3",
    "rapidfuzz>=3.0.0",
    "scikit-learn>=1.9.1",
    "setuptools<70",
    "ydata-profiling>=4.18.4",
]
